from django.db import models
# Create your models here.
from django.contrib.gis.db import models

"""
现在，你只需要记住，改变模型需要这三步：
    (1)编辑 models.py 文件，改变模型。
    (2)运行 python manage.py makemigrations 为模型的改变生成迁移文件。
    (3)运行 python manage.py migrate 来应用数据库迁移。
"""

class FigureSpot(models.Model):
    """
    figurespotnumber: String (20.0)
    country: String (20.0)
    village: String (24.0)
    illegalparty: String (105.0)
    illegalconstructionname: String (75.0)
    cityorvillage: String (5.0)
    detailedaddress: String (100.0)
    startworkingtime: String (20.0)
    buildingprogress: String (50.0)
    constructiontype: String (50.0)
    housingbuildingnumber: String (20.0)
    illegaloccupationarea: String (30.0)
    illegalbuildingtype: String (250.0)
    dsrsf: String (20.0)
    househome: String (9.0)
    figurespotsource: Real (0.0)
    collectiveeconomymember: String (3.0)
    remarks: String (254.0)
    housinglayernumber: String (20.0)
    whetherillegal: String (3.0)
    illegalfloorarea: String (30.0)
    id: Real (0.0)
    objectid: Real (0.0)
    sxm: String (254.0)
    sxdm: String (254.0)
    sxxzqdm: String (254.0)
    sfhyhx: String (254.0)
    sfld: String (254.0)
    sfjbnt: String (254.0)
    sfxzjsyd: String (254.0)
    sfkfbj: String (254.0)
    sfzgjsyd: String (254.0)
    sflyhx: String (254.0)
    xzqhdm: String (20.0)
    sfgyl: String (50.0)
    fwlx: String (20.0)
    sfxz: String (20.0)
    yearperiods: String (10.0)
    figurespotstate: Real (0.0)
    buildingtype: String (50.0)
    wftbjh: String (20.0)
    zcr: String (20.0)
    zcspr: String (20.0)
    cjr: String (20.0)
    wfspr: String (20.0)
    xhspr: String (20.0)
    xhtime: Real (0.0)
    shape_Length: Real (0.0)
    shape_Area: Real (0.0)
    """
    figurespotnumber = models.CharField(max_length=20)
    country = models.CharField(max_length=20)
    village = models.CharField(max_length=24)
    illegalparty = models.CharField(max_length=104)
    illegalconstructionname = models.CharField(max_length=75)
    cityorvillage = models.CharField(max_length=5)
    detailedaddress = models.CharField(max_length=100)
    startworkingtime = models.CharField(max_length=20)
    buildingprogress = models.CharField(max_length=50)
    constructiontype = models.CharField(max_length=50)
    housingbuildingnumber = models.CharField(max_length=20)
    illegaloccupationarea = models.CharField(max_length=30)
    illegalbuildingtype = models.CharField(max_length=250)
    dsrsf = models.CharField(max_length=20)
    househome = models.CharField(max_length=9)
    figurespotsource =  models.DecimalField(max_digits=10, decimal_places=0)
    collectiveeconomymember = models.CharField(max_length=3)
    remarks = models.CharField(max_length=255)
    housinglayernumber = models.CharField(max_length=20)
    whetherillegal = models.CharField(max_length=3)
    illegalfloorarea = models.CharField(max_length=30)
    id =  models.DecimalField(max_digits=10, decimal_places=0, primary_key=True)
    objectid =  models.DecimalField(max_digits=10, decimal_places=0)
    sxm = models.CharField(max_length=255)
    sxdm = models.CharField(max_length=255)
    sxxzqdm = models.CharField(max_length=255)
    sfhyhx = models.CharField(max_length=255)
    sfld = models.CharField(max_length=255)
    sfjbnt = models.CharField(max_length=255)
    sfxzjsyd = models.CharField(max_length=255)
    sfkfbj = models.CharField(max_length=255)
    sfzgjsyd = models.CharField(max_length=255)
    sflyhx = models.CharField(max_length=255)
    xzqhdm = models.CharField(max_length=255)
    sfgyl = models.CharField(max_length=50)
    fwlx = models.CharField(max_length=20)
    sfxz = models.CharField(max_length=20)
    yearperiods = models.CharField(max_length=10)
    figurespotstate =  models.DecimalField(max_digits=10, decimal_places=0)
    buildingtype = models.CharField(max_length=50)
    wftbjh = models.CharField(max_length=20)
    zcr = models.CharField(max_length=20)
    zcspr = models.CharField(max_length=20)
    cjr = models.CharField(max_length=20)
    wfspr = models.CharField(max_length=20)
    xhspr = models.CharField(max_length=20)
    xhtime =  models.DecimalField(max_digits=10, decimal_places=0)
    shape_Length =  models.DecimalField(max_digits=10, decimal_places=3)
    shape_Area =  models.DecimalField(max_digits=10, decimal_places=3)
    # GEOS
    geom = models.MultiPolygonField(srid=4490)
    def __str__(self):
        return self.figurespotnumber


class ZengWei(models.Model):
    """
    fwlx: String (254.0)
    sfxz: String (254.0)
    sxm: String (254.0)
    sxdm: String (254.0)
    tbbh: String (254.0)
    sxxzqdm: String (254.0)
    xzqhdm: String (254.0)
    xzmc: String (254.0)
    sfxzjsyd: String (254.0)
    sfzgjsyd: String (254.0)
    sflyhx: String (254.0)
    sfhyhx: String (254.0)
    sfkfbj: String (254.0)
    sfjbnt: String (254.0)
    sfld: String (254.0)
    sfgyl: String (254.0)
    xzcmc: String (254.0)
    mj: Real (24.15)
    bz: String (254.0)
    pic: String (254.0)
    shape_leng: Real (24.15)
    yearperiod: String (50.0)
    """
    fwlx = models.CharField(max_length=255)
    sfxz = models.CharField(max_length=255)
    sxm = models.CharField(max_length=255)
    sxdm = models.CharField(max_length=255)
    tbbh = models.CharField(max_length=255)
    sxxzqdm = models.CharField(max_length=255)
    xzqhdm = models.CharField(max_length=255)
    xzmc = models.CharField(max_length=255)
    sfxzjsyd = models.CharField(max_length=255)
    sfzgjsyd = models.CharField(max_length=255)
    sflyhx = models.CharField(max_length=255)
    sfhyhx = models.CharField(max_length=255)
    sfkfbj = models.CharField(max_length=255)
    sfjbnt = models.CharField(max_length=255)
    sfld = models.CharField(max_length=255)
    sfgyl = models.CharField(max_length=255)
    xzcmc = models.CharField(max_length=255)
    mj = models.DecimalField(max_digits=10, decimal_places=3)
    bz = models.CharField(max_length=255)
    pic = models.CharField(max_length=255)
    shape_leng = models.DecimalField(max_digits=10, decimal_places=3)
    yearperiod = models.CharField(max_length=255)
    shape_Length = models.DecimalField(max_digits=10, decimal_places=3)
    shape_Area =  models.DecimalField(max_digits=10, decimal_places=3)
    # GEOS FIELD
    geom = models.MultiPolygonField(srid = 4490) # 自定义srs

    objects = models.Manager() #自己声明查询器
    def __str__(self):
        return self.tbbh