# Generated by Django 2.2.4 on 2019-09-03 09:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigureSpot',
            fields=[
                ('figurespotnumber', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=24)),
                ('illegalparty', models.CharField(max_length=104)),
                ('illegalconstructionname', models.CharField(max_length=75)),
                ('cityorvillage', models.CharField(max_length=5)),
                ('detailedaddress', models.CharField(max_length=100)),
                ('startworkingtime', models.CharField(max_length=20)),
                ('buildingprogress', models.CharField(max_length=50)),
                ('constructiontype', models.CharField(max_length=50)),
                ('housingbuildingnumber', models.CharField(max_length=20)),
                ('illegaloccupationarea', models.CharField(max_length=30)),
                ('illegalbuildingtype', models.CharField(max_length=250)),
                ('dsrsf', models.CharField(max_length=20)),
                ('househome', models.CharField(max_length=9)),
                ('figurespotsource', models.DecimalField(decimal_places=0, max_digits=10)),
                ('collectiveeconomymember', models.CharField(max_length=3)),
                ('remarks', models.CharField(max_length=255)),
                ('housinglayernumber', models.CharField(max_length=20)),
                ('whetherillegal', models.CharField(max_length=3)),
                ('illegalfloorarea', models.CharField(max_length=30)),
                ('id', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('objectid', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sxm', models.CharField(max_length=255)),
                ('sxdm', models.CharField(max_length=255)),
                ('sxxzqdm', models.CharField(max_length=255)),
                ('sfhyhx', models.CharField(max_length=255)),
                ('sfld', models.CharField(max_length=255)),
                ('sfjbnt', models.CharField(max_length=255)),
                ('sfxzjsyd', models.CharField(max_length=255)),
                ('sfkfbj', models.CharField(max_length=255)),
                ('sfzgjsyd', models.CharField(max_length=255)),
                ('sflyhx', models.CharField(max_length=255)),
                ('xzqhdm', models.CharField(max_length=255)),
                ('sfgy', models.CharField(max_length=50)),
                ('fwlx', models.CharField(max_length=20)),
                ('sfxz', models.CharField(max_length=20)),
                ('yearperiods', models.CharField(max_length=10)),
                ('figurespotstate', models.DecimalField(decimal_places=0, max_digits=10)),
                ('buildingtype', models.CharField(max_length=50)),
                ('wftbjh', models.CharField(max_length=20)),
                ('zcr', models.CharField(max_length=20)),
                ('zcspr', models.CharField(max_length=20)),
                ('cjr', models.CharField(max_length=20)),
                ('wfspr', models.CharField(max_length=20)),
                ('xhspr', models.CharField(max_length=20)),
                ('xhtime', models.DecimalField(decimal_places=0, max_digits=10)),
                ('shape_Length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shape_Area', models.DecimalField(decimal_places=3, max_digits=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4490)),
            ],
        ),
        migrations.CreateModel(
            name='ZengWei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fwlx', models.CharField(max_length=255)),
                ('sfxz', models.CharField(max_length=255)),
                ('sxm', models.CharField(max_length=255)),
                ('sxdm', models.CharField(max_length=255)),
                ('tbbh', models.CharField(max_length=255)),
                ('sxxzqdm', models.CharField(max_length=255)),
                ('xzqhdm', models.CharField(max_length=255)),
                ('xzmc', models.CharField(max_length=255)),
                ('sfxzjsyd', models.CharField(max_length=255)),
                ('sfzgjsyd', models.CharField(max_length=255)),
                ('sflyhx', models.CharField(max_length=255)),
                ('sfhyhx', models.CharField(max_length=255)),
                ('sfkfbj', models.CharField(max_length=255)),
                ('sfjbnt', models.CharField(max_length=255)),
                ('sfld', models.CharField(max_length=255)),
                ('sfgyl', models.CharField(max_length=255)),
                ('xzcmc', models.CharField(max_length=255)),
                ('mj', models.DecimalField(decimal_places=3, max_digits=10)),
                ('bz', models.CharField(max_length=255)),
                ('pic', models.CharField(max_length=255)),
                ('shape_leng', models.DecimalField(decimal_places=3, max_digits=10)),
                ('yearperiod', models.CharField(max_length=255)),
                ('shape_Length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('shape_Area', models.DecimalField(decimal_places=3, max_digits=10)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4490)),
            ],
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
"""
BEGIN;
--
-- Create model FigureSpot
--
CREATE TABLE "report_figurespot" ("figurespotnumber" varchar(20) NOT NULL, "country" varchar(20) NOT NULL, "village" varchar(24) NOT NULL, "illegalparty" varchar(104) NOT NULL, "illegalconstructionname" varchar(75) NOT NULL, "cityorvillage" varchar(5) NOT NULL, "detailedaddress" varchar(100) NOT NULL, "startworkingtime" varchar(20) NOT NULL, "buildingprogress" varchar(50) NOT NULL, "constructiontype" varchar(50) NOT NULL, "housingbuildingnumber" varchar(20) NOT NULL, "illegaloccupationarea" varchar(30) NOT NULL, "illegalbuildingtype" varchar(250) NOT NULL, "dsrsf" varchar(20) NOT NULL, "househome" varchar(9) NOT NULL, "figurespotsource" numeric(10, 0) NOT NULL, "collectiveeconomymember" varchar(3) NOT NULL, "remarks" varchar(255) NOT NULL, "housinglayernumber" varchar(20) NOT NULL, "whetherillegal" varchar(3) NOT NULL, "illegalfloorarea" varchar(30) NOT NULL, "id" numeric(10, 0) NOT NULL PRIMARY KEY, "objectid" numeric(10, 0) NOT NULL, "sxm" varchar(255) NOT NULL, "sxdm" varchar(255) NOT NULL, "sxxzqdm" varchar(255) NOT NULL, "sfhyhx" varchar(255) NOT NULL, "sfld" varchar(255) NOT NULL, "sfjbnt" varchar(255) NOT NULL, "sfxzjsyd" varchar(255) NOT NULL, "sfkfbj" varchar(255) NOT NULL, "sfzgjsyd" varchar(255) NOT NULL, "sflyhx" varchar(255) NOT NULL, "xzqhdm" varchar(255) NOT NULL, "sfgy" varchar(50) NOT NULL, "fwlx" varchar(20) NOT NULL, "sfxz" varchar(20) NOT NULL, "yearperiods" varchar(10) NOT NULL, "figurespotstate" numeric(10, 0) NOT NULL, "buildingtype" varchar(50) NOT NULL, "wftbjh" varchar(20) NOT NULL, "zcr" varchar(20) NOT NULL, "zcspr" varchar(20) NOT NULL, "cjr" varchar(20) NOT NULL, "wfspr" varchar(20) NOT NULL, "xhspr" varchar(20) NOT NULL, "xhtime" numeric(10, 0) NOT NULL, "shape_Length" numeric(10, 3) NOT NULL, "shape_Area" numeric(10, 3) NOT NULL, "geom" geometry(MULTIPOLYGON,4490) NOT NULL);
--
-- Create model ZengWei
--
CREATE TABLE "report_zengwei" ("id" serial NOT NULL PRIMARY KEY, "fwlx" varchar(255) NOT NULL, "sfxz" varchar(255) NOT NULL, "sxm" varchar(255) NOT NULL, "sxdm" varchar(255) NOT NULL, "tbbh" varchar(255) NOT NULL, "sxxzqdm" varchar(255) NOT NULL, "xzqhdm" varchar(255) NOT NULL, "xzmc" varchar(255) NOT NULL, "sfxzjsyd" varchar(255) NOT NULL, "sfzgjsyd" varchar(255) NOT NULL, "sflyhx" varchar(255) NOT NULL, "sfhyhx" varchar(255) NOT NULL, "sfkfbj" varchar(255) NOT NULL, "sfjbnt" varchar(255) NOT NULL, "sfld" varchar(255) NOT NULL, "sfgyl" varchar(255) NOT NULL, "xzcmc" varchar(255) NOT NULL, "mj" numeric(10, 3) NOT NULL, "bz" varchar(255) NOT NULL, "pic" varchar(255) NOT NULL, "shape_leng" numeric(10, 3) NOT NULL, "yearperiod" varchar(255) NOT NULL, "shape_Length" numeric(10, 3) NOT NULL, "shape_Area" numeric(10, 3) NOT NULL, "geom" geometry(MULTIPOLYGON,4490) NOT NULL);
--
-- Delete model WorldBorder
--
DROP TABLE "report_worldborder" CASCADE;
CREATE INDEX "report_figurespot_geom_id" ON "report_figurespot"USING GIST ("geom");
CREATE INDEX "report_zengwei_geom_id" ON "report_zengwei"USING GIST ("geom");
COMMIT;

"""