# Generated by Django 2.2.4 on 2019-09-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190903_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figurespot',
            old_name='sfgy',
            new_name='sfgyl',
        ),
    ]
